Stack View
tr1ckyf0x/Stolovka pull request #2
Opened 2022-01-21 03:47 UTC by NikitaShvadlenko

Implemented main screen view via stack view.
Major issues: 
1) CollectionView and CollectionViewManager are both using enum Constants. In order to make changes, developer must change two files: one for CollectionVIew, another one for Delegate.  - suggestion - create a protocol for Constants, code values for Constants in: either View Controller, or builder. 
2) Please check whether the function calls for buttons in cells are done in the right places.

2022-01-21 18:04 UTC, tr1ckyf0x requested changes

2022-01-22 06:35 UTC, NikitaShvadlenko commented on Stolovka/Packages/SmokersStolovka/Sources/SmokersStolovka/MainMenu/StolovkaMainScreenPresenter.swift
> +        mainScreen.reloadCategorizedItemsCollection()
I believe I must do the dispatch queue here. 
It is faster to reload everything than fetch new information. 
Would you like me to use DispatchQueue?

2022-01-27 17:03 UTC, tr1ckyf0x approved these changes

2022-01-27 17:04 UTC, tr1ckyf0x commented on Stolovka/Packages/SmokersStolovka/Sources/SmokersStolovka/MainMenu/StolovkaMainScreenPresenter.swift
> +        mainScreen.reloadCategorizedItemsCollection()
Read more about multithreading, and, especially, about race condition

2022-01-28 22:43 UTC, merged