Added AddToCartUseCase
tr1ckyf0x/Stolovka pull request #3
Opened 2022-02-17 17:29 UTC by NikitaShvadlenko

Please check whether the use case implementation is correct. 

Manager<-Use Case<-Presenter<-ViewController

2022-03-03 23:46 UTC, NikitaShvadlenko commented on Stolovka/Packages/SmokersStolovka/Sources/SmokersStolovka/MainMenu/ViewController.swift
> +        guard let foodItem = foodCollectionViewCell.foodItem else { return }
What is the best way to go about getting the index path of the cell?

2022-03-10 11:56 UTC, tr1ckyf0x requested changes

2022-03-10 11:56 UTC, tr1ckyf0x commented on Stolovka/Packages/SmokersStolovka/Sources/SmokersStolovka/MainMenu/Managers/ShoppingCartManager.swift
> +    func removeFromCart(foodItem: FoodItem)
Here should be completion closure too, as this method is also considered to be asynchronous

2022-03-10 11:56 UTC, tr1ckyf0x commented on Stolovka/Packages/SmokersStolovka/Sources/SmokersStolovka/MainMenu/Managers/ShoppingCartManager.swift
> +    func fetchCartItems(foodItems: [FoodItem])
I do not deem it to have a `foodItems` argument, as you `fetch` items which are already contained in the cart. I suppose that there must be a completion closure, which will have `Result<[FoodItem], Error>` as argument

2022-03-10 11:56 UTC, tr1ckyf0x commented on Stolovka/Packages/SmokersStolovka/Sources/SmokersStolovka/MainMenu/Managers/ShoppingCartManager.swift
> +    var shoppingCart: [FoodItem] = []
This property must be private.

2022-03-10 11:56 UTC, tr1ckyf0x commented on Stolovka/Packages/SmokersStolovka/Sources/SmokersStolovka/MainMenu/Managers/ShoppingCartManager.swift
> +        print("ShoppingCart Items are \(String(describing: shoppingCart))")
Completion not called

2022-03-10 11:56 UTC, tr1ckyf0x commented on Stolovka/Packages/SmokersStolovka/Sources/SmokersStolovka/MainMenu/Managers/ShoppingCartManager.swift
> +    func addToCart(foodItem: FoodItem, completion: @escaping (Result<Any, Error>) -> Void)
`Any` is not proper argument if you do not suppose to pass anything to this closure. `Void` is more appropriate

2022-03-10 11:56 UTC, tr1ckyf0x commented on Stolovka/Packages/SmokersStolovka/Sources/SmokersStolovka/MainMenu/StolovkaMainScreenContract.swift
> +    func viewDidTapAddButton(foodItem: FoodItem)
Previously discussed, that `view` must not pass `FoodItem` directly. It should tell presenter which `IndexPath` has triggered the action

2022-03-10 11:56 UTC, tr1ckyf0x commented on Stolovka/Packages/SmokersStolovka/Sources/SmokersStolovka/MainMenu/StolovkaMainScreenPresenter.swift
> +    var addToCartUseCase: AsyncUseCase<FoodItem, Any>?
Use `Void` instead of `Any` as this use case is not considered to return any value

2022-03-10 11:56 UTC, tr1ckyf0x commented on Stolovka/Packages/SmokersStolovka/Sources/SmokersStolovka/MainMenu/StolovkaMainScreenPresenter.swift
> +    func viewDidTapAddButton(foodItem: FoodItem) {
Told previously that `view` must not pass `FoodItem` directly. You should have an `indexPath` instead, and get `FoodItem` by this `indexPath`, which will be passed to `UseCase`

2022-03-10 11:56 UTC, tr1ckyf0x commented on Stolovka/Packages/SmokersStolovka/Sources/SmokersStolovka/MainMenu/UseCases/AddToCartUseCase.swift
> +//  File.swift
Pay attention to file headers

2022-03-10 11:56 UTC, tr1ckyf0x commented on Stolovka/Packages/SmokersStolovka/Sources/SmokersStolovka/MainMenu/UseCases/AddToCartUseCase.swift
> +class AddToCartUseCase: AsyncUseCase<FoodItem, Any> {
This use case is not intended to return any value, use `Void`

2022-03-10 11:56 UTC, tr1ckyf0x commented on Stolovka/Packages/SmokersStolovka/Sources/SmokersStolovka/MainMenu/UseCases/AddToCartUseCase.swift
> +    var shoppingCart: ShoppingCartManagerProtocol
This property must be private. In addition, it is not mutated anywhere, consequently, may be declared as `let`

2022-03-10 11:56 UTC, tr1ckyf0x commented on Stolovka/Packages/SmokersStolovka/Sources/SmokersStolovka/MainMenu/ViewController.swift
> +        guard let foodItem = foodCollectionViewCell.foodItem else { return }
https://developer.apple.com/documentation/uikit/uicollectionview/1618094-indexpath

2022-03-10 11:56 UTC, tr1ckyf0x commented on Stolovka/Packages/SmokersStolovka/Sources/SmokersStolovka/MainMenu/Views/FoodCollectionViewCell.swift
> +            delegate?.foodCollectionViewCellDidPressLikeButton(foodCollectionViewCell: self, likeButtonPressedFor: foodItem)
The same about `FoodItem` and `IndexPath`

2022-03-11 13:12 UTC, tr1ckyf0x requested changes

2022-03-11 13:12 UTC, tr1ckyf0x commented on Stolovka/Packages/SmokersStolovka/Sources/SmokersStolovka/MainMenu/Managers/ShoppingCartManager.swift
> +    func fetchCartItems(completion: @escaping (Result<Void, Error>) -> Void)
Here instead of `Void` should be `[FoodItem]`
```suggestion
    func fetchCartItems(completion: @escaping (Result<[FoodItem], Error>) -> Void)
```

2022-03-11 13:12 UTC, tr1ckyf0x commented on Stolovka/Packages/SmokersStolovka/Sources/SmokersStolovka/MainMenu/Model/FoodItemCarouselManager.swift
> +    func getFoodItem(at indexPath: IndexPath) -> FoodItem {
I am not sure that this method is still required

2022-03-12 07:37 UTC, tr1ckyf0x approved these changes

2022-03-12 07:44 UTC, merged